### ISSUE TITLE
C library source code

### ISSUE THREAD

**Issue by jofemodo** [marko-pi/MCP4728#1]
Hi Marko!
Do you intend to release the C library  source code? I would like to use it for the zynthian project ...
Thanks

**Comment by marko-pi** [comment]
Hello Jośe,

I do intend to share the code, but I intend to do some final improvements before that.  In the moment I have something else on my breadboard, but I think I could do it over the weekend.

Marko

**Comment by jofemodo** [comment]
This would be fantastic!
Thanks!

**Comment by marko-pi** [comment]
The source code is released.
